#!/usr/bin/env python3
import sys
from pathlib import Path
from arc import decode
import yaml
CONFIG_FILE = Path(__file__).parent/'data'/'old.yml'
decoder = decode.Decoder(yaml.safe_load(CONFIG_FILE.open()))


def main():
    for t in map(str.rstrip, sys.stdin):
        print(t)
        for word in decoder.decode(t):
            word.prune()
            print(word)
        print()


if __name__ == '__main__':
    main()
